import * as fs from "fs";
import * as path from "path";
import { ReportData } from "./types.js";
import { getDataDir } from "./config.js";

export function generateReport(data: ReportData): string {
  const lines = [
    `# dreamwatch Report`,
    ``,
    `**Task:** ${data.task}`,
    `**Status:** ${data.status}`,
    `**Started:** ${data.startedAt}`,
    `**Completed:** ${data.completedAt}`,
    `**Duration:** ${data.duration}`,
    `**Budget:** $${data.budgetUsed.toFixed(2)} / $${data.budgetLimit.toFixed(2)}`,
    ``,
  ];
  
  if (data.prUrl) {
    lines.push(`**Pull Request:** ${data.prUrl}`, ``);
  }
  
  if (data.summary.length > 0) {
    lines.push(`## Summary`, ``);
    data.summary.forEach(line => lines.push(line));
    lines.push(``);
  }
  
  lines.push(`---`, `Generated by dreamwatch at ${data.completedAt}`);
  
  return lines.join("\n");
}

export function saveReport(report: string): string {
  const reportsDir = path.join(getDataDir(), "reports");
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }
  
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").split("T")[0];
  const filename = `${timestamp}.md`;
  const reportPath = path.join(reportsDir, filename);
  
  // If file exists, append a number
  let counter = 1;
  let finalPath = reportPath;
  while (fs.existsSync(finalPath)) {
    const base = path.basename(reportPath, ".md");
    finalPath = path.join(reportsDir, `${base}-${counter}.md`);
    counter++;
  }
  
  fs.writeFileSync(finalPath, report, "utf8");
  return finalPath;
}

export function getLatestReport(): string | null {
  const reportsDir = path.join(getDataDir(), "reports");
  
  if (!fs.existsSync(reportsDir)) {
    return null;
  }
  
  const files = fs.readdirSync(reportsDir)
    .filter(f => f.endsWith(".md"))
    .map(f => ({
      name: f,
      path: path.join(reportsDir, f),
      mtime: fs.statSync(path.join(reportsDir, f)).mtime,
    }))
    .sort((a, b) => b.mtime.getTime() - a.mtime.getTime());
  
  if (files.length === 0) {
    return null;
  }
  
  return fs.readFileSync(files[0].path, "utf8");
}
